server:
  port: 0

spring:
  application:
    name: gd-main-service # application id

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8761/eureka # microservices registration

