server:
  port: 0

spring:
  application:
    name: gd-main-service # application id
  datasource:
    hikari:
      data-source-properties:
        stringtype: unspecified
    tomcat:
      db-properties:
        stringtype: unspecified
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/gym_dev
    username: postgres
    password: Relhzijd24
  flyway:
    url: jdbc:postgresql://localhost:5432/gym_dev
    locations: classpath:db.migration
    user: postgres
    password: Relhzijd24
  jpa:
    properties:
      hibernate:
        show_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        hbm2ddl:
          auto: none
    open-in-view: false
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8761/eureka # microservices registration

gym:
  mail:
    enabled: true
    host: smtp.yandex.ru
    username: Cross.Fit.SPB@yandex.ru
    password: Crossfit584
    port: 465
    protocol: smtps
