server:
  port: 9999

http-book-service:
  httpMethod: POST
  httpUrl: http://localhost:9999/api/v1/book/save
  mediaType: "application/json"
  setting:
    connectTimeout: 10000s

spring:
  application:
    name: gd-main-service # application id
  datasource:
    hikari:
      data-source-properties:
        stringtype: unspecified
    tomcat:
      db-properties:
        stringtype: unspecified
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/gym_dev
    username: postgres
    password: xumuk
  jpa:
    properties:
      hibernate:
        show_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        hbm2ddl:
          auto: none
    open-in-view: false
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8761/eureka # microservices registration

gym:
  mail:
    enabled: true
    host: smtp.yandex.ru
    username: -----------------
    password: --------
    port: 465
    protocol: smtps


cxf:
  path: /note
