ALTER TABLE note
    ALTER COLUMN status TYPE varchar USING status::varchar;

CREATE TABLE note_history
(
    id               int primary key generated by default as identity,
    section          varchar not null,
    advice           varchar not null,
    date_of_creation date,
    who_created      varchar,
    status           varchar
);

CREATE TABLE note_history_comment
(
    id               int primary key generated by default as identity,
    note_history_id  int references note_history (id) on delete cascade,
    text             varchar not null,
    author           varchar not null,
    date_of_creation timestamp(0)
);