server:
  port: 8761

spring:
  application:
    name: gd-eureka-server # application id

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      default-zone: http://localhost:8081/eureka # microservices registration

