server:
  port: 0

spring:
  application:
    name: gd-store-service # application id
  datasource:
    hikari:
      data-source-properties:
        stringtype: unspecified
    tomcat:
      db-properties:
        stringtype: unspecified
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/gym_store_dev
    username: postgres
    password: xumuk
  servlet:
    multipart:
      max-file-size: 500MB
      enabled: true

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka # microservices registration
    fetch-registry: true
    register-with-eureka: true

s3:
  url: http://127.0.0.1:9090
  accessKey: VUrjTH56pB1b7kIfQX5u
  secretKey: xcbcH62zsi9ouRd5aawvGCNK9zl43PKMnNvg7MpF
  bucketName: gd-store


