server:
  port: 0

spring:
  application:
    name: gd-store-service # application id
  datasource:
    hikari:
      data-source-properties:
        stringtype: unspecified
    tomcat:
      db-properties:
        stringtype: unspecified
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/gym_dev
    username: postgres
    password: Relhzijd24
  flyway:
    url: jdbc:postgresql://localhost:5432/gym_dev
    locations: classpath:db.migration
    user: postgres
    password: Relhzijd24

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka # microservices registration
    fetch-registry: true
    register-with-eureka: true

grpc:
  server:
    port: 8090


