server:
  port: 0
  servlet:
    context-path: /auth-service

spring:
  application:
    name: gd-auth-service # application id

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka # microservices registration
    fetch-registry: true
    register-with-eureka: true
  instance:
    preferIpAddress: true

jwt:
  secret: B9vPHGM8C0ia4uOuxxqPD5DTbWC9F9TWvPStp3pb7ARo0oK2mJ3pd3YG4lxA9i8bj6OTbadwezxgeEByY
  expiration-time: 86400000
