CREATE TABLE admin
(
    id           uuid primary key,
    name         varchar               not null,
    phone_number varchar               not null,
    email        varchar               NOT NULL,
    age          int check ( age > 0 ) not null,
    birth_date   date                  not null
);

CREATE TABLE note
(
    id               int primary key generated by default as identity,
    section          varchar not null,
    advice           varchar not null,
    date_of_creation date,
    who_created      varchar,
    status           varchar
);
CREATE TABLE person
(
    id         bigint generated by default as identity primary key,
    name       varchar               not null,
    age        int check ( age > 0 ) not null,
    birth_date date                  not null,
    email      varchar               not null,
    country    varchar               not null,
    extra_info jsonb
);
CREATE TABLE question
(
    id                  bigint generated by default as identity PRIMARY KEY,
    issue               varchar not null,
    section             varchar not null,
    who_asked           varchar not null,
    developers_response varchar
);
CREATE TABLE answer
(
    id           bigint primary key generated by default as identity,
    question_id  bigint references question (id) on delete cascade,
    response     varchar not null,
    who_answered varchar,
    likes        bigint
);
CREATE TABLE note_comment
(
    id               int primary key generated by default as identity,
    note_id          int references note (id) on delete cascade,
    text             varchar not null,
    author           varchar not null,
    date_of_creation timestamp(0)
);
CREATE TABLE note_history
(
    id               int primary key generated by default as identity,
    section          varchar not null,
    advice           varchar not null,
    date_of_creation date,
    who_created      varchar,
    status           varchar
);